// Parses rubric.txt and writes:
//   supabase/schema.sql   – tables + rubric_criteria seed rows (run once in the Supabase SQL editor)
//   lib/rubric-seed.json  – same rubric, used by the local (no-Supabase) dev store
//   lib/schema-sql.ts     – the SQL as a string, so the app can create its own tables on first run
// Runs automatically before `npm run dev` / `npm run build`.
// Run with: npm run schema
import fs from 'node:fs';

const txt = fs.readFileSync(new URL('../rubric.txt', import.meta.url), 'utf8');

function parseSection(role, startMarker, endMarker) {
  const start = txt.indexOf(startMarker);
  const end = endMarker ? txt.indexOf(endMarker, start + 1) : txt.length;
  const block = txt.slice(start, end);
  const parts = block.split('Criterion name:').slice(1);
  return parts.map((p, i) => {
    const name = p.split('\n')[0].trim();
    const desc = (p.match(/What a strong candidate looks like:\s*([\s\S]*?)\nWeight:/) || [])[1]?.trim();
    const weight = parseInt((p.match(/Weight:\s*(\d+)%/) || [])[1], 10);
    const source = (p.match(/Source:\s*(.*)/) || [])[1]?.trim() || '';
    if (!name || !desc || !weight) throw new Error(`Could not parse criterion ${i + 1} for ${role}`);
    return { role, name, description: desc, weight, source, position: i + 1 };
  });
}

const pm = parseSection('PM', 'PRODUCT MANAGER (PM)\n', 'SENIOR PRODUCT MANAGER (SPM)\n');
const spm = parseSection('SPM', 'SENIOR PRODUCT MANAGER (SPM)\n', null);
for (const [r, list] of [['PM', pm], ['SPM', spm]]) {
  const total = list.reduce((s, c) => s + c.weight, 0);
  if (total !== 100) throw new Error(`${r} weights add to ${total}, expected 100`);
  if (list.length < 4 || list.length > 6) throw new Error(`${r} must have 4-6 criteria`);
}
const all = [...pm, ...spm];
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const sql = `-- Kargo Hiring Dashboard — database schema
-- Paste this whole file into Supabase → SQL Editor → Run. Safe to re-run.

create extension if not exists pgcrypto;

-- The rubric every candidate is scored against (one row per criterion per role).
create table if not exists rubric_criteria (
  id          serial primary key,
  role        text not null check (role in ('PM','SPM')),
  name        text not null,
  description text not null,
  weight      int  not null check (weight between 1 and 100),
  source      text,
  position    int  not null default 0,
  unique (role, name)
);

-- Candidate record. Contains NO personal details: cv_content is the CV with name/email/phone stripped.
create table if not exists candidates (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  file_name       text,
  applied_role    text not null check (applied_role in ('PM','SPM')),
  status          text not null default 'processing' check (status in ('processing','scored','error')),
  error           text,
  cv_content      text,
  scores          jsonb,
  pm_score        numeric,
  spm_score       numeric,
  decision        text not null default 'auto' check (decision in ('auto','invite','reject')),
  brief           text,
  email_kind      text check (email_kind in ('invite','reject')),
  email_subject   text,
  email_body      text,
  email_edited    boolean not null default false,
  sent_at         timestamptz,
  sent_to         text,
  sent_message_id text
);
create index if not exists candidates_role_idx on candidates (applied_role);

-- Personal details live in their own table and are never sent to any AI step.
create table if not exists candidate_pii (
  candidate_id uuid primary key references candidates(id) on delete cascade,
  name         text,
  email        text,
  phone        text
);

-- Lock the tables down: only the server (service-role key) can read or write.
alter table rubric_criteria enable row level security;
alter table candidates      enable row level security;
alter table candidate_pii   enable row level security;

-- Rubric seed — generated from rubric.txt by scripts/build-schema.mjs
delete from rubric_criteria;
insert into rubric_criteria (role, name, description, weight, source, position) values
${all.map((c) => `  (${q(c.role)}, ${q(c.name)}, ${q(c.description)}, ${c.weight}, ${q(c.source)}, ${c.position})`).join(',\n')};
`;

fs.mkdirSync(new URL('../supabase/', import.meta.url), { recursive: true });
fs.writeFileSync(new URL('../supabase/schema.sql', import.meta.url), sql);
fs.writeFileSync(new URL('../lib/rubric-seed.json', import.meta.url), JSON.stringify(all, null, 2) + '\n');
fs.writeFileSync(new URL('../lib/schema-sql.ts', import.meta.url), '// Generated by scripts/build-schema.mjs — do not edit.\nexport const SCHEMA_SQL = ' + JSON.stringify(sql) + ';\n');
console.log(`Wrote supabase/schema.sql, lib/rubric-seed.json, lib/schema-sql.ts — ${pm.length} PM + ${spm.length} SPM criteria.`);
